# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
version: 2
updates:
  - package-ecosystem: npm
    schedule:
      interval: daily
    allow:
      - dependency-name: "@map-colonies/schemas"
        dependency-type: direct
    directory: /
    commit-message:
      prefix: "build(deps)"
  - package-ecosystem: github-actions
    schedule: 
      interval: weekly
    commit-message:
      prefix: "ci(deps)"
    directory: "/"
