# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
version: 2
updates:
  # schemas
  - package-ecosystem: npm
    schedule:
      interval: daily
    allow:
      - dependency-name: "@map-colonies/schemas"
    directory: /
    labels:
      - 'infra'
    commit-message:
      prefix: "deps"
  # deps
  - package-ecosystem: npm
    schedule:
      interval: weekly
    allow:
      - dependency-type: production
    ignore:
      - dependency-name: "@map-colonies/schemas"
    directory: /
    commit-message:
      prefix: "deps"
    groups:
      map-colonies:
        patterns:
          - "@map-colonies/*"
      opentelemetry:
        patterns:
          - "@opentelemetry/*"
      patch:
        update-types:
          - patch
  # dev-deps
  - package-ecosystem: npm
    schedule:
      interval: weekly
    allow:
      - dependency-type: development
    ignore:
      - dependency-name: "@map-colonies/schemas"
    directory: /
    labels:
      - 'infra'
    commit-message:
      prefix: "devdeps"
    groups:
      map-colonies:
        patterns:
          - "@map-colonies/*"
      opentelemetry:
        patterns:
          - "@opentelemetry/*"
      types:
        patterns:
          - "@types/*"
      dev-patch:
        update-types:
          - patch
    
  # github deps
  - package-ecosystem: github-actions
    schedule: 
      interval: weekly
    commit-message:
      prefix: "ci"
    directory: "/"
    labels:
      - 'infra'
