{{- $releaseName := .Release.Name -}}
{{- $chartName := include "config-server.name" . -}}
{{- if and .Values.enabled (not .Values.dbConfig.useExternalSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "config-server.fullname" . }}
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    release: {{ $releaseName }}
    {{- include "config-server.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.dbConfig.username | b64enc }}
  password: {{ .Values.dbConfig.password | b64enc }}
{{- end }}
