{{- $releaseName := .Release.Name -}}
{{- $chartName := include "config-server.name" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-secret" (include "config-server.fullname" .) }}
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "config-server.environment" . }}
    release: {{ $releaseName }}
    {{- include "config-server.labels" . | nindent 4 }}
type: Opaque
data:
  DB_USERNAME: {{ .Values.dbConfig.username | b64enc }}
  DB_PASSWORD: {{ .Values.dbConfig.password | b64enc }}
{{- end }}
