{
 "title": "config-server BI",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "config_ui_base_url", "query": "${VAR_CONFIG_UI_BASE_URL}" }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \r\n\tcount(*) as total_configs,\r\n\tcount(distinct name) as unique_configs\r\nfrom config_server.config"
    },
    {
     "rawSql": "select count(*) reference_count from config_server.config_refs\r\n"
    }
   ]
  },
  {
   "title": "The 5 configs with the highest version",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "select name, version, schema_id, created_at\r\nfrom config_server.config\r\norder by version desc\r\nlimit 5"
    }
   ]
  },
  {
   "title": "Configs with references",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "rawSql": "WITH RECURSIVE descendants AS\r\n\t(SELECT\r\n\t \tname as start_name,\r\n\t \tversion as start_version,\r\n\t\tname, \r\n\t\tversion, \r\n\t\tis_latest,\r\n\t\t0 AS depth\r\n\tfrom config_server.config\r\nUNION\r\n\t(SELECT d.start_name, d.start_version, config.name, config.version, config.is_latest, d.depth + 1\r\n\tFROM descendants d\r\n\tinner join \"config_server\".\"config_refs\" on (\"config_refs\".\"name\" = d.\"name\" and \"config_refs\".\"version\" = d.\"version\") \r\n\tinner join \r\n          \"config_server\".\"config\" on \r\n            (\"config_refs\".\"ref_name\" = \"config\".\"name\" and \r\n              (\"config\".\"version\" = \"config_refs\".\"ref_version\" or \r\n                (\"config_refs\".\"ref_version\" is null and \"config\".\"is_latest\" = true))))\r\n\t\t)\t\t\r\nSELECT\r\n      start_name as name, start_version as version, count(*) - 1 as \"Number of references\", max(depth) as depth\r\n    FROM\r\n      descendants\r\n\t  group by start_name, start_version\r\n\t  having count(*) - 1 > 0"
    }
   ]
  },
  {
   "title": "Most common schemas in use",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "select schema_id as \"Schema\", count(*)\r\nfrom config_server.config\r\ngroup by schema_id\r\norder by count(*) desc\r\nLIMIT 5"
    }
   ]
  },
  {
   "title": "Latest created configs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "rawSql": "select name, version, created_at as \"Created at\"\r\nfrom config_server.config\r\norder by created_at desc\r\nlimit 5"
    }
   ]
  }
 ]
}