{
 "title": "config-server",
 "time": { "from": "2024-10-19T05:35:38.988Z", "to": "2024-10-19T06:29:36.458Z" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(nodejs_version_info{app_kubernetes_io_name=\"config-server\"},namespace)"
    }
   },
   {
    "name": "release",
    "query": {
     "query": "label_values(nodejs_version_info{namespace=\"$namespace\",app_kubernetes_io_name=\"config-server\"},release)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(nodejs_version_info{namespace=\"$namespace\",release=\"$release\",app_kubernetes_io_name=\"config-server\"},pod)"
    }
   },
   { "name": "config_ui_base_url", "query": "${VAR_CONFIG_UI_BASE_URL}" },
   {
    "name": "operations",
    "query": {
     "query": "label_values(http_request_duration_seconds_count{namespace=\"$namespace\",release=\"$release\",app_kubernetes_io_name=\"config-server\", pod=~\"$pod\"},operation)"
    }
   },
   { "name": "options", "query": "status_code,operation,method" }
  ]
 },
 "panels": [
  {
   "title": "Operation average response time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 19, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (http_request_duration_seconds_sum{app=\"config-server\",release=\"infra-config\",namespace=\"infra-services\",pod=~\".*\",}) by (operation)\r\n / \r\n sum (http_request_duration_seconds_count{app=\"config-server\",release=\"infra-config\",namespace=\"infra-services\",pod=~\".*\",}) by (operation)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "App version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "service_version{namespace=\"$namespace\",release=\"$release\",pod=~\"$pod\"}",
     "legendFormat": "v{{service_version_major}}.{{service_version_minor}}.{{service_version_patch}}"
    }
   ]
  },
  {
   "title": "requests in time range",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{app=\"config-server\",release=\"infra-config\",namespace=\"infra-services\",pod=~\".*\",}[$__range])) by (status_code,operation)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "requests in time range per $options",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 16 },
   "repeat": "options",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{app=\"config-server\",release=\"infra-config\",namespace=\"infra-services\",pod=~\".*\",}[$__range])) by ($options)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Per pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "$pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "repeat": "pod",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{app=\"config-server\",release=\"$release\",namespace=\"$namespace\",pod=~\"$pod\",operation=~\"$operations\"}[$__interval])) by (pod)\r\n/ \r\nsum(rate(http_request_duration_seconds_count{app=\"config-server\",release=\"$release\",namespace=\"$namespace\",pod=~\"$pod\",operation=~\"$operations\"}[$__interval])) by (pod)",
     "legendFormat": "average"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{app=\"config-server\",release=\"$release\",namespace=\"$namespace\",pod=~\"$pod\",operation=~\"$operations\"}[$__interval])) by (le,pod))",
     "legendFormat": "median"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket{app=\"config-server\",release=\"$release\",namespace=\"$namespace\",pod=~\"$pod\",operation=~\"$operations\"}[$__interval])) by (le,pod))",
     "legendFormat": "p90"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{app=\"config-server\",release=\"$release\",namespace=\"$namespace\",pod=~\"$pod\",operation=~\"$operations\"}[$__interval])) by (pod)",
     "legendFormat": "amount"
    }
   ]
  },
  { "title": "Stats by $options", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 }, "repeat": "options" },
  {
   "title": "Requests per $__interval window",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{app=\"config-server\",release=\"$release\",namespace=\"$namespace\",pod=~\"$pod\",operation=~\"$operations\"}[$__interval])) by ($options)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Median request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{app=\"config-server\",release=\"$release\",namespace=\"$namespace\",pod=~\"$pod\",operation=~\"$operations\"}[$__interval])) by (le,$options))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{app=\"config-server\",release=\"$release\",namespace=\"$namespace\",pod=~\"$pod\",operation=~\"$operations\"}[$__interval])) by ($options)\r\n/ \r\nsum(rate(http_request_duration_seconds_count{app=\"config-server\",release=\"$release\",namespace=\"$namespace\",pod=~\"$pod\",operation=~\"$operations\"}[$__interval])) by ($options)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "0.9 quantile request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket{app=\"config-server\",release=\"$release\",namespace=\"$namespace\",pod=~\"$pod\",}[$__interval])) by (le, $options))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}